### ISSUE TITLE
Fabric-loader creates empty jar, which crashes minecraft

### ISSUE THREAD

**Issue by jqlifice** [FabricMC/fabric-installer#116]
hi,
installing fabric with the fabric installer it creates an empty jar in the versions folder (which is expected behavior, from my previous research?).
Interestingly on attempting to launch into the Fabric version the game crashes with an "ZipException: zip file is empty" while attempting to read the empty file
```
Uncaught exception in thread "main"
net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: java.io.IOException: error reading /home/jonas/.minecraft/versions/fabric-loader-0.14.14-1.19.3/fabric-loader-0.14.14-1.19.3.jar
	at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:232)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: error reading /home/jonas/.minecraft/versions/fabric-loader-0.14.14-1.19.3/fabric-loader-0.14.14-1.19.3.jar
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:214)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:161)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:187)
	... 4 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:201)
	... 6 more

```

Reinstalling creates an empty jar again

**Comment by jqlifice** [comment]
UPDATE:
This actually was a file permission error, the fabric installer didnt work with my user, so I ran it as root.

in case someone has the same issue and stumbles across this chown -R the version folder fixed it for me.
