### ISSUE TITLE
it did not install

### ISSUE THREAD

**Issue by Towery-too** [FabricMC/fabric-installer#148]
um hi i would like to report this error

java.lang.NullPointerException  at net.fabricmc.installer.util.Library. (Library.java:37)  at net.fabricmc.installer.client.ClientInstaller.install(ClientInstaller.java:61)  at net.fabricmc.installer.client.ClientHandler.lambda$doInstall$1(ClientHandler.java:105)  at java.lang.Thread.run(Unknown Source

i got it after i install it 

it does it every time that i downloaded this spasific version of 1.16.5 
and here's the loader version 0.2.0.71

**Comment by Towery-too** [comment]
older execept 0.3.0 below

**Comment by modmuss50** [comment]
Use a newer loader version, that version came out in 2018, 6 years ago. An older installer may work but you are very much on your own.
