### ISSUE TITLE
Can't start Fabric Installer

### ISSUE THREAD

**Issue by Jerozgen** [FabricMC/fabric-installer#15]
I can't start Fabric Installer because connection refused.

_Console:_
C:\Users\Jerozgen\Desktop> java -jar fabric-installer-0.4.2.26.jar
Loading Fabric Installer: 0.4.2.26
Exception in thread "main" java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at net.fabricmc.installer.util.MavenHandler.load(MavenHandler.java:51)
        at net.fabricmc.installer.InstallerGui.<init>(InstallerGui.java:41)
        at net.fabricmc.installer.InstallerGui.start(InstallerGui.java:60)
        at net.fabricmc.installer.Main.main(Main.java:69)

**Comment by pan93412** [comment]
Check your internet connection first.

**Comment by Jerozgen** [comment]
Yeah, I don't have connection with https://maven.fabricmc.net/.
You could add a notification with connection error when a user double-clicks the app.

**Comment by modmuss50** [comment]
Should now show an error dialog with the newer version.
