### ISSUE TITLE
Missing sounds

### ISSUE THREAD

**Issue by Chocohead** [FabricMC/fabric-installer#4]
If a vanilla snapshot isn't launched the installer appears to fail to download some assets, primarily sounds. Having looked into it further it appears if the parent version (as defined from `inheritsFrom`) doesn't exist the launcher starts guessing where to download assets:
```
[ERROR]: Couldn't download resources
java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/indexes/1.14.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_144]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getResourceFiles(MinecraftVersionManager.java:274) [launcher.jar:1.6.89-j]
	at net.minecraft.launcher.updater.MinecraftVersionManager.downloadResources(MinecraftVersionManager.java:256) [launcher.jar:1.6.89-j]
	at com.mojang.launcher.game.runner.AbstractGameRunner.downloadRequiredFiles(AbstractGameRunner.java:123) [launcher.jar:1.6.89-j]
	at net.minecraft.launcher.game.MinecraftGameRunner.downloadRequiredFiles(MinecraftGameRunner.java:96) [launcher.jar:1.6.89-j]
	at com.mojang.launcher.game.runner.AbstractGameRunner.playGame(AbstractGameRunner.java:110) [launcher.jar:1.6.89-j]
	at net.minecraft.launcher.game.GameLaunchDispatcher$1.run(GameLaunchDispatcher.java:111) [launcher.jar:1.6.89-j]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[INFO]: Download job 'Resources' skipped as there are no files to download
[INFO]: Job 'Resources' finished successfully (took 0:00:00.000)
```
Which then leads to
```[FATAL]: Fatal error launching game. Report this to http://bugs.mojang.com please!
java.io.FileNotFoundException: File '~\.minecraft\assets\indexes\1.14.json' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[launcher.jar:1.6.89-j]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.Launcher.cleanupOrphanedAssets(Launcher.java:298) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.Launcher.performCleanups(Launcher.java:540) ~[launcher.jar:1.6.89-j]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:209) ~[launcher.jar:1.6.89-j]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:186) [launcher.jar:1.6.89-j]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:122) [launcher.jar:1.6.89-j]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:1.6.89-j]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher.jar:1.6.89-j]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```
If the parent has been previously loaded (so that in `~/.minecraft/version/parent` has the full `parent.jar` saved) it manages to properly load all assets. Oddly enough textures manage to download fine however, likely from being bundled as part of the `parent.jar` itself.

Whilst this is probably on Mojang, it might be worth seeing if there is a viable workaround to force all the assets to download correctly or putting a warning that launching the vanilla snapshot first is necessary. The `assetsIndex` `url` is where the launcher is probably getting the valid assets from (as opposed to `assets` alone), so maybe that could be manually extracted if the parent isn't found?

**Comment by modmuss50** [comment]
I think the easiest and safest way will be to require the version to be launched first.

Opening an issue about it with mojang might not be a bad idea as well.

**Comment by modmuss50** [comment]
Is this still an issue? Ive not heard of it being reported

**Comment by Chocohead** [comment]
Just so it's clear this is with the older Java launcher so it is reasonably likely that the newer Electron one never had the problem in the first place. Nothing has changed on the asset front since being originally reported though, using 1.16-rc1:
```
java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/indexes/1.16.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_144]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launcher.updater.MinecraftVersionManager.getResourceFiles(MinecraftVersionManager.java:274) [launcher.jar:1.6.93]
	at net.minecraft.launcher.updater.MinecraftVersionManager.downloadResources(MinecraftVersionManager.java:256) [launcher.jar:1.6.93]
	at com.mojang.launcher.game.runner.AbstractGameRunner.downloadRequiredFiles(AbstractGameRunner.java:123) [launcher.jar:1.6.93]
	at net.minecraft.launcher.game.MinecraftGameRunner.downloadRequiredFiles(MinecraftGameRunner.java:96) [launcher.jar:1.6.93]
	at com.mojang.launcher.game.runner.AbstractGameRunner.playGame(AbstractGameRunner.java:110) [launcher.jar:1.6.93]
	at net.minecraft.launcher.game.GameLaunchDispatcher$1.run(GameLaunchDispatcher.java:111) [launcher.jar:1.6.93]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```
```
java.io.FileNotFoundException: File '~/.minecraft/assets/indexes/1.16.json' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[launcher.jar:1.6.93]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711) ~[launcher.jar:1.6.93]
	at net.minecraft.launcher.Launcher.cleanupOrphanedAssets(Launcher.java:298) ~[launcher.jar:1.6.93]
	at net.minecraft.launcher.Launcher.performCleanups(Launcher.java:540) ~[launcher.jar:1.6.93]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:209) ~[launcher.jar:1.6.93]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:186) [launcher.jar:1.6.93]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:122) [launcher.jar:1.6.93]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:1.6.93]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher.jar:1.6.93]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```
Although things have changed more generally, e365e57 has broken installs completely as without a `type` the launcher will skip the profile with a warning:
```
Ignoring: versions/fabric-loader-0.8.8+build.202-1.16-rc1/fabric-loader-0.8.8+build.202-1.16-rc1.json; it has an invalid version specified
```
The launcher apparently is quite insistent that every profile has a type, regardless of the profile it might be extending.

**Comment by modmuss50** [comment]
ok, I will revert that change. It worked on the new launcher.

**Comment by modmuss50** [comment]
Closing this, as I dont think there is anything else to do here. The old jar launcher is unsupported as far as I know
