### ISSUE TITLE
Install failure, /home/$user doesn't exist

### ISSUE THREAD

**Issue by EmilyBjoerk** [FabricMC/fabric-installer#58]
I'm trying to install fabric on my dedicated linux MC server. I put the universal jar installer in the minecraft folder and ran: ` sudo -u minecraft java -jar fabric-installer-0.6.1.51.jar server -dir . -mcversion 1.16.4`

And get:

```
Loading Fabric Installer: 0.6.1.51
Using latest loader version
Installing Fabric Loader 0.10.6+build.214(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:102)
Caused by: java.io.IOException: Could not create /home/minecraft/.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:50)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:100)
```

Minecraft is installed under `/opt/minecraft-1.16.4/` and ran as user `minecraft`. The user `minecraft` is a system user with non existent home directory `/home/minecraft` and with shell set to `/bin/nologin`.  There are multiple minecraft instances running under this user.

The install script tries to install something into the user's home folder. This limits the use of multiple different minecraft versions and is likely to fail with systems that are securely configured (e.g. service accounts don't have home directories).

**Comment by Sparky1492** [comment]
I've ran into the same issue, with very slightly different setup.  I'm working on getting Fabric working with [Crafty Controller](https://gitlab.com/crafty-controller/crafty-web) that also setups a user with no home directory.

OS:
  uname -a 
```
Linux SERVERNAME 5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Commands ran:
```
java -jar fabric-installer-0.6.1.51.jar server
```
```
java -jar fabric-installer-0.6.1.51.jar server -dir . -mcversion 1.16.4
```

Error returned:

```
crafty@SERFVERNAME:/var/opt/minecraft/fabrictest$ java -jar fabric-installer-0.6.1.51.jar server
Loading Fabric Installer: 0.6.1.51
Using latest loader version
Using latest game version
Installing Fabric Loader 0.10.8(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
	at net.fabricmc.installer.Main.main(Main.java:102)
Caused by: java.io.IOException: Could not create /home/crafty/.cache/fabric-installer/libraries!
	at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:50)
	at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
	at net.fabricmc.installer.Main.main(Main.java:100)
```


@EmilyBjoerk Were you able to get anything working with this?

**Comment by EmilyBjoerk** [comment]
I did, I think I temporarily set the home dir to /var/tmp, not sure if I actually cleared it later tho..

**Comment by Sparky1492** [comment]
@EmilyBjoerk , Thank you for the reply.
