### ISSUE TITLE
Fabric installer appears to wish for root directory access. Fails install.

### ISSUE THREAD

**Issue by sfxworks** [FabricMC/fabric-installer#64]
Hello,
```
[init] Running as uid=1001 gid=1000 with /data as 'drwxrwxrwx    2 1001     1000             1 Mar 10 21:30 /data'
[init] Resolved version given 1.16.4 into 1.16.4
[init] Resolving type given FABRIC
[init] Checking Fabric version information.
[init] Downloading installer version 0.7.2
[init] ...trying https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.2/fabric-installer-0.7.2.jar
[init] Installing Fabric using /tmp/fabric-installer-0.7.2.jar
Loading Fabric Installer: 0.7.2
Using latest loader version
Installing Fabric Loader 0.11.2(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.IOException: Could not create /.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:51)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:77)
Loading Fabric Installer: 0.7.2
Using latest loader version
Installing Fabric Loader 0.11.2(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.IOException: Could not create /.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:51)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:77)
Loading Fabric Installer: 0.7.2
Using latest loader version
Installing Fabric Loader 0.11.2(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:79)
Caused by: java.io.IOException: Could not create /.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:51)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:77)
[init] Fabric failed to install after several tries.
```
When trying to install fabric using the fabric-installer, fabric appears to try to write to /.cache. This fails to work in scenarios where permissions from the /data directory and root directory are different. itgz looked into this issue at https://github.com/itzg/docker-minecraft-server/issues/797#issuecomment-797069429 as it uses the Minecraft docker image, but even with `-dir` specified now it appears to still try to write to `/.cache/fabric-installer/libraries` rather than `/data/.cache/fabric-installer/libraries`

**Comment by modmuss50** [comment]
I will take a look at this, I dont see a reason why the installer cache shouldnt be in the install dir.
