### ISSUE TITLE
Checks for ASM minor version break when ASM classes are bundled with `fabric-server-launch.jar`

### ISSUE THREAD

**Issue by sirtrollraptor** [FabricMC/fabric-installer#94]
SpongePowered Mixin uses a version check on ASM to detect if the compatibility level of a mixin is supported.

* `JAVA_16` checks if the major version is 9 or above, which has no problems.
* `JAVA_17` /`JAVA_18` checks if the major version is 9 or above and, for ASM 9, the minor version is 1/2 or above, respectively.

Mixin checks the version by [checking the ASM package's implementation version](https://github.com/FabricMC/Mixin/blob/21b9d4714f47d7dcc47008a46b285cd217a74644/src/main/java/org/spongepowered/asm/util/asm/ASM.java#L212-L224), which is specified in `META-INF/MANIFEST.MF`.

The Fabric installer does not copy this version information across when bundling ASM 9.2, so the version check by Mixin only detects it as ASM 9.0.

Relevant stack trace:
```
java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
        at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
```

A workaround for this is to add these lines to `META-INF/MANIFEST.MF`:
```
Name: org/objectweb/asm/
Implementation-Version: 9.2
```

**Comment by modmuss50** [comment]
https://github.com/FabricMC/fabric-loader/pull/558 and https://github.com/FabricMC/fabric-installer/pull/93 solve this issue by not bundling the jars into one. 

The work around might be a good idea to do for now 👍

**Comment by modmuss50** [comment]
This has been fixed.
